import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/landing_page/Header";
import { getSession } from "@/services/authServices";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartQuiz",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSession();

  return (
    <html lang="en">
      <body
        className={`${outfit.className} flex min-h-dvh flex-col bg-blue-50 text-zinc-700 antialiased`}
      >
        <main className="flex min-h-screen flex-col text-gray-900">
          <Header user={user} />
          {children}
        </main>
      </body>
    </html>
  );
}
